//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CustomData
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ValidationDbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ValidationDbEntities object using the connection string found in the 'ValidationDbEntities' section of the application configuration file.
        /// </summary>
        public ValidationDbEntities() : base("name=ValidationDbEntities", "ValidationDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ValidationDbEntities object.
        /// </summary>
        public ValidationDbEntities(string connectionString) : base(connectionString, "ValidationDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ValidationDbEntities object.
        /// </summary>
        public ValidationDbEntities(EntityConnection connection) : base(connection, "ValidationDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ErrorMessage> ErrorMessages
        {
            get
            {
                if ((_ErrorMessages == null))
                {
                    _ErrorMessages = base.CreateObjectSet<ErrorMessage>("ErrorMessages");
                }
                return _ErrorMessages;
            }
        }
        private ObjectSet<ErrorMessage> _ErrorMessages;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ErrorMessages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToErrorMessages(ErrorMessage errorMessage)
        {
            base.AddObject("ErrorMessages", errorMessage);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ValidationDbModel", Name="ErrorMessage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ErrorMessage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ErrorMessage object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static ErrorMessage CreateErrorMessage(global::System.Int32 id)
        {
            ErrorMessage errorMessage = new ErrorMessage();
            errorMessage.Id = id;
            return errorMessage;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorCode
        {
            get
            {
                return _ErrorCode;
            }
            set
            {
                OnErrorCodeChanging(value);
                ReportPropertyChanging("ErrorCode");
                _ErrorCode = StructuralObject.SetValidValue(value, true, "ErrorCode");
                ReportPropertyChanged("ErrorCode");
                OnErrorCodeChanged();
            }
        }
        private global::System.String _ErrorCode;
        partial void OnErrorCodeChanging(global::System.String value);
        partial void OnErrorCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorMessageText
        {
            get
            {
                return _ErrorMessageText;
            }
            set
            {
                OnErrorMessageTextChanging(value);
                ReportPropertyChanging("ErrorMessageText");
                _ErrorMessageText = StructuralObject.SetValidValue(value, true, "ErrorMessageText");
                ReportPropertyChanged("ErrorMessageText");
                OnErrorMessageTextChanged();
            }
        }
        private global::System.String _ErrorMessageText;
        partial void OnErrorMessageTextChanging(global::System.String value);
        partial void OnErrorMessageTextChanged();

        #endregion

    }

    #endregion

}
